CREATE TABLE public.apps (
    id bigint NOT NULL,
    pub_id character(24) NOT NULL,
    workspace_id bigint NOT NULL,
    title character varying(64) NOT NULL,
    "desc" character varying(512),
    icon character varying(24),
    active boolean not null default(true),
    options bigint not null default(0),
    schema text not null,
    created_by_id bigint NOT NULL,
    created_at timestamp NOT NULL,
    updated_by_id bigint,
    updated_at timestamp,
    deleted_by_id bigint,
    deleted_at timestamp,
    published_at timestamp,
    published_by_id bigint
);

ALTER TABLE ONLY public.apps
    ADD CONSTRAINT apps_pkey PRIMARY KEY (id);

ALTER TABLE public.apps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.apps
    ADD CONSTRAINT apps_pub_id_key UNIQUE (pub_id);

create index on public.apps(workspace_id, title);

CREATE TABLE public.apps_auths (
    id bigint NOT NULL,
    pub_id character(24) NOT NULL,
    app_id bigint NOT NULL,
    user_id bigint,
    group_id bigint,
    reverse boolean NOT NULL,
    created_by_id bigint NOT NULL,
    created_at timestamp NOT NULL,
    updated_by_id bigint,
    updated_at timestamp
);

ALTER TABLE ONLY public.apps_auths
    ADD CONSTRAINT apps_auths_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.apps_auths
    ADD CONSTRAINT apps_auths_pub_id_key UNIQUE (pub_id);

ALTER TABLE public.apps_auths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_auths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
