
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.robotikflow.core.services.formula.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int POW = 19;
  public static final int GTEQ = 25;
  public static final int MULT = 6;
  public static final int INTEGER_LIT = 33;
  public static final int LTEQ = 24;
  public static final int LPAREN = 11;
  public static final int NULL_LIT = 38;
  public static final int MINUS = 15;
  public static final int RPAREN = 12;
  public static final int OROR = 31;
  public static final int NOT = 16;
  public static final int SEMICOLON = 5;
  public static final int AND = 28;
  public static final int LT = 22;
  public static final int OR = 29;
  public static final int COMMA = 7;
  public static final int DIV = 17;
  public static final int ANDAND = 30;
  public static final int PLUS = 14;
  public static final int DOT = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQEQ = 26;
  public static final int MOD = 18;
  public static final int EQ = 10;
  public static final int FLOATING_POINT_LIT = 34;
  public static final int LBRACK = 2;
  public static final int COLON = 13;
  public static final int BOOLEAN_LIT = 35;
  public static final int LBRACE = 8;
  public static final int RBRACK = 3;
  public static final int RBRACE = 9;
  public static final int QUESTION = 32;
  public static final int LSHIFT = 20;
  public static final int STRING_LIT = 36;
  public static final int GT = 23;
  public static final int RSHIFT = 21;
  public static final int NOTEQ = 27;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PLUS",
  "MINUS",
  "NOT",
  "DIV",
  "MOD",
  "POW",
  "LSHIFT",
  "RSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "AND",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "INTEGER_LIT",
  "FLOATING_POINT_LIT",
  "BOOLEAN_LIT",
  "STRING_LIT",
  "IDENTIFIER",
  "NULL_LIT"
  };
}

